### ISSUE TITLE
Write CLI instructions (this issue holds all the screenshots that are in the README.md and in docs/*.md)

### ISSUE THREAD

**Issue by maelvls** [jetstack/jetstack-secure-gcm#21]
As discussed in https://github.com/jetstack/jsp-gcm/issues/16#issuecomment-779936375, the "Deploy documentation URL" field is mandatory (see in the below screenshot and in the [solution release page](https://console.cloud.google.com/partner/editor/jetstack-public/jetstack-secure-for-cert-manager?project=jetstack-public&authuser=2&form=addTrackPanel))

![release-form-deploy-cli-doc-url](https://user-images.githubusercontent.com/2195781/108088758-1de78d00-7079-11eb-8a82-a51aa67211ed.png)

![](https://user-images.githubusercontent.com/2195781/108091915-72d8d280-707c-11eb-925a-2a7d09226fa1.png)

Here is what Gitlab has set for [their](https://console.cloud.google.com/marketplace/kubernetes/config/google/gitlab?version=13.5&project=jetstack-mael-valais&authuser=2) "Deploy documentation URL":

- Public Git repo: https://github.com/GoogleCloudPlatform/click-to-deploy
- Deploy documentation URL: https://github.com/GoogleCloudPlatform/click-to-deploy/blob/master/k8s/gitlab/README.md

<img width="600" alt="gitlab-cli-instructions" src="https://user-images.githubusercontent.com/2195781/108091613-2b524680-707c-11eb-8f26-e472623d231a.png">

I think we could do something similar but that would require us to make the jsp-gcm repo public:

- Public Git repo: https://github.com/jetstack/jsp-gcm
- Deploy documentation URL: https://cert-manager.io/docs/installation/google-cloud-marketplace (to be created)

Examples of such readmes:
- [Hedera Mirror Node](https://console.cloud.google.com/marketplace/details/mirror-node-public/hedera-mirror-node?authuser=2) (free) has their CLI deploy documentation in the [README.md](https://github.com/hashgraph/hedera-mirror-node/tree/59b70d3/charts/marketplace/gcp#command-line-instructions) of the GCM repo
- [Unleash Enterprise](https://console.cloud.google.com/marketplace/details/bricks-software-public/unleash-enterprise?pli=1&authuser=2) (paid offering) also has the CLI deploy documentation on their [README.md](https://github.com/unleash-hosted/unleash-hosted-gcp-marketplace/tree/fa094ec3c9d7f533b87482f3e13c4f155d7f8f62#command-line-instructions)

**Comment by maelvls** [comment]
<img src="https://user-images.githubusercontent.com/2195781/110091031-491bed00-7d98-11eb-8522-ddc91913d010.png" width="500" alt="Only the minor version 1.1 should be pushed, not 1.1.0 or 1.1.0-gcm.1. This screenshot is stored in this issue: https://github.com/jetstack/jetstack-secure-gcm/issues/21">

**Comment by maelvls** [comment]
<img src="https://user-images.githubusercontent.com/2195781/110688721-3105fc80-81e2-11eb-9297-81e65dc8baa0.png" width="500" alt="The app must be purchased once by someone with access to the billing account. The project does not matter. After having it purchased once, any project that is attached to this billing account will be able to Configure the application. This screenshot is stored in this issue: https://github.com/jetstack/jetstack-secure-gcm/issues/21">

**Comment by maelvls** [comment]
<img src="https://user-images.githubusercontent.com/2195781/110706910-daf08380-81f8-11eb-92ef-d62ef7ff4de1.png" width="300" alt="To update the already released minor version, first open the existing minor version by clicking on the version itself (it is a link). This screenshot is stored in this issue: https://github.com/jetstack/jetstack-secure-gcm/issues/21">

<img src="https://user-images.githubusercontent.com/2195781/110706906-d9bf5680-81f8-11eb-909f-faa1818b8f56.png" width="300" alt="Then, click on Update images and Save. This screenshot is stored in this issue: https://github.com/jetstack/jetstack-secure-gcm/issues/21">

**Comment by maelvls** [comment]
<img src="https://user-images.githubusercontent.com/2195781/110790775-c0a6bc00-8271-11eb-9ea4-c701ef7f58a1.png" width="300" alt="To download the lincese.yaml file, click on Download license key. This screenshot is stored in this issue: https://github.com/jetstack/jetstack-secure-gcm/issues/21">

**Comment by maelvls** [comment]
<img src="https://user-images.githubusercontent.com/2195781/110791519-9acde700-8272-11eb-81f4-4f27fb8a174d.png" width="300" alt="The application page on GKE should show the test-1 application. The preflight deployment is failing because the user has not (yet) gone to http://platform.jetstack.io/ to register their cluster. This screenshot is stored in this issue: https://github.com/jetstack/jetstack-secure-gcm/issues/21">

**Comment by maelvls** [comment]
<img src="https://user-images.githubusercontent.com/2195781/110807883-bf7e8a80-8283-11eb-9d0d-57be5c063d3d.png" width="500" alt="The certificate example-cert shows in the UI at platform.jetstack.io. This screenshot is stored in this issue: https://github.com/jetstack/jetstack-secure-gcm/issues/21">

**Comment by maelvls** [comment]
<img src="https://user-images.githubusercontent.com/2195781/111179435-5e6cf480-85ac-11eb-81d4-22c21923adf3.png" width="300" alt="The solution admin page has a button 'Submit for review' at the bottom that must be clicked in order to get the new version reviewed by Google. This screenshot is stored in this issue: https://github.com/jetstack/jetstack-secure-gcm/issues/21">

**Comment by maelvls** [comment]
<img src="https://user-images.githubusercontent.com/2195781/112529074-28e2bb00-8da5-11eb-9aca-f347fbfe0330.png" width="300" alt="The Application view on GKE after deploying the application test-1 onto the test-1 namespace. This screenshot is stored in this issue: https://github.com/jetstack/jetstack-secure-gcm/issues/21">

**Comment by davidsbond** [comment]
![image](https://user-images.githubusercontent.com/6227720/115693127-8b54ba00-a357-11eb-8aca-0604933f73ce.png)

**Comment by davidsbond** [comment]
![image](https://user-images.githubusercontent.com/6227720/115693498-e5557f80-a357-11eb-9635-69e2c64afc98.png)

**Comment by davidsbond** [comment]
![image](https://user-images.githubusercontent.com/6227720/115696486-a4ab3580-a35a-11eb-9412-6282963a279d.png)

**Comment by davidsbond** [comment]
![image](https://user-images.githubusercontent.com/6227720/115697227-492d7780-a35b-11eb-8e27-d5778118f5a7.png)

**Comment by davidsbond** [comment]
![image](https://user-images.githubusercontent.com/6227720/115697669-a6c1c400-a35b-11eb-851f-ee1e962a8df2.png)

**Comment by davidsbond** [comment]
Resized images, forgot I've uploaded huge ones.

![image](https://user-images.githubusercontent.com/6227720/116088112-777fbf80-a699-11eb-8f08-418a8777917a.png)
![image](https://user-images.githubusercontent.com/6227720/116088269-9ed68c80-a699-11eb-9676-01a0fa5f0e5c.png)
![image](https://user-images.githubusercontent.com/6227720/116088589-eb21cc80-a699-11eb-8f1d-48804ecbffd9.png)
![image](https://user-images.githubusercontent.com/6227720/116088811-1e645b80-a69a-11eb-8ea7-8489cb8124f9.png)
