### ISSUE TITLE
On a fresh one-click deploy, the preflight is always red, leading to a poor UX

### ISSUE THREAD

**Issue by maelvls** [jetstack/jetstack-secure-gcm#41]
There is still [a discussion](https://github.com/jetstack/jetstack-secure-gcm/pull/35#discussion_r593230708) we are having with @wallrj about the poor UX regarding the failing preflight deployment: when a user clicks "Deploy", he should be expecting everything green. But currently, the preflight deployment stays failing until the user proceeds with [step 2](https://platform.jetstack.io/docs/google-cloud-marketplace#step-2-log-into-the-jetstack-secure-dashboard). What I did to remediate this is to explain to the user in [step 1](https://platform.jetstack.io/docs/google-cloud-marketplace#step-1-install-jestack-secure-for-cert-manager) that the failing preflight deployment is expected and that they should go on with installing the preflight agent to get it fixed.

<img alt="" src="https://user-images.githubusercontent.com/2195781/110791519-9acde700-8272-11eb-81f4-4f27fb8a174d.png" width="500">

**Comment by maelvls** [comment]
I received [this email](https://groups.google.com/a/jetstack.io/g/cert-manager-maintainers/c/lQo2Ct5VMt4/m/QMMo5wzJBQAJ) (jetstack internal link) where Dinesh asks me to fix our app because he sees that the preflight deployment fails.

> I deployed your listing on to one of our test clusters and noticed that the prefligt deployment is failing with the following error 
> ```
> configmap "agent-config" not found
> ```
> Can you please update the ConfigMap name to "ubbagent-config" instead of "agent-config" in the preflight deployment and resubmit the draft for a review.

In my previous email, I had preemptively told him that the `preflight` deployment was expected to fail and that it was part of our "normal" flow and that it is documented in the user guide:

> I just re-submitted the application with the new release [1.1.0-gcm.6](https://github.com/jetstack/jetstack-secure-gcm/releases/tag/1.1.0-gcm.6). This fixes the notes and description on the Application view. Note that the preflight deployment [is expected to be failing](https://platform.jetstack.io/docs/google-cloud-marketplace#step-1-install-jestack-secure-for-cert-manager) on a fresh click-to-deploy or CLI installation.

**Comment by maelvls** [comment]
**Plan:** have the `preflight` deployment scaled to 0 by default. I'll change the user documentation: when the user wants to enable preflight, they will have to type one more command (in [README.md](https://github.com/jetstack/jetstack-secure-gcm/blob/main/README.md#step-2-log-into-the-jetstack-secure-dashboard)):

```diff
 sed '/namespace:/d' agent-config.yaml | kubectl -n $NAMESPACE apply -f-
 kubectl -n $NAMESPACE rollout restart $(kubectl -n $NAMESPACE get deploy -oname | grep preflight)
+kubectl -n $NAMESPACE scale --replicas=1 $(kubectl -n $NAMESPACE get deploy -oname | grep preflight)
```

**Timeline:** I will have a new release 1.1.0-gcm.8 by this evening and re-submit to Google.

fyi @mattbates @wallrj @charlieegan3

**Comment by charlieegan3** [comment]
I think this works for now. Ideally we have a tighter integration here in future.

**Comment by charlieegan3** [comment]
@mattbates this seems like a clear priority for the next jscp sprint.
