### ISSUE TITLE
Branch 1.4: 1.4.3-gcm.0 failing review

### ISSUE THREAD

**Issue by maelvls** [jetstack/jetstack-secure-gcm#65]
@wallrj and I have submitted 1.4.3-gcm.0 yesterday (https://github.com/jetstack/jetstack-secure-gcm/pull/64). The review failed, here is the email Dinesh sent:

I hope all is well with you! The latest submitted draft was reviewed and noticed that the tester pod is failing at our verification service with the following error. The smoke test file is [smoke-test.t](https://github.com/jetstack/jetstack-secure-gcm/blob/release-1.4/smoke-test.t).

```diff
At least 1 test failed or timed out.

--- smoke-test.t
+++ smoke-test.t.err
@@ -29,8 +29,9 @@
   >   issuerRef:
   >     name: selfsigned-issuer
   > EOF
-  issuer.cert-manager.io/selfsigned-issuer created
-  certificate.cert-manager.io/selfsigned-cert created
+  unable to recognize "STDIN": no matches for kind "Certificate" in version "cert-manager.io/v1"
+  Error from server (InternalError): error when creating "STDIN": Internal error occurred: failed calling webhook "webhook.cert-manager.io": Post "https://cert-manager-webhook.apptest-ad05456g.svc:443/mutate?timeout=10s": service "cert-manager-webhook" not found
+  [1]

 Now, let us wait until the Certificate becomes Ready. An error here might
 indicate that the cert-manager-controller is running but keeps failing at the
@@ -39,21 +40,24 @@
 available.

   $ kubectl wait -n ${NAMESPACE} --for=condition=Ready --timeout=2m certificate selfsigned-cert
-  certificate.cert-manager.io/selfsigned-cert condition met
+  error: the server doesn't have a resource type "certificate"
+  [1]

 Get the Secret associated to the Certificate:

   $ kubectl get secret -n ${NAMESPACE} selfsigned-cert-tls
-  NAME                  TYPE                DATA   AGE
-  selfsigned-cert-tls   kubernetes.io/tls   3      * (glob)
+  Error from server (NotFound): secrets "selfsigned-cert-tls" not found
+  [1]

 Delete the self-signed Issuer and the Certificate:

   $ kubectl delete -n ${NAMESPACE} issuer selfsigned-issuer
-  issuer.cert-manager.io "selfsigned-issuer" deleted
+  Error from server (NotFound): issuers.cert-manager.io "selfsigned-issuer" not found
+  [1]

   $ kubectl delete -n ${NAMESPACE} certificate selfsigned-cert
-  certificate.cert-manager.io "selfsigned-cert" deleted
+  error: the server doesn't have a resource type "certificate"
+  [1]


 Create a GoogleCASIssuer and a Certificate:
@@ -86,7 +90,8 @@
   >     name: googlecas-issuer
   > EOF
   googlecasissuer.cas-issuer.jetstack.io/googlecas-issuer created
-  certificate.cert-manager.io/googlecas-cert created
+  error: unable to recognize "STDIN": no matches for kind "Certificate" in version "cert-manager.io/v1"
+  [1]

 We don't know yet how, as part of this smoke test file, to create a GCP service
 account and then create a Kubernetes service account and bind the two together
@@ -102,4 +107,5 @@
   googlecasissuer.cas-issuer.jetstack.io "googlecas-issuer" deleted

   $ kubectl delete -n ${NAMESPACE} certificate googlecas-cert
-  certificate.cert-manager.io "googlecas-cert" deleted
+  error: the server doesn't have a resource type "certificate"
+  [1]

# Ran 1 tests, 0 skipped, 1 failed.
```

Can you please confirm that the mpdev verification passed in your local for the [latest deployer image](http://gcr.io/jetstack-public/jetstack-secure-for-cert-manager/deployer@sha256:62dab3167397f710c00b7d7826576bcb5b4b7a03696c3704f7eb5646f7583c2e)? If so, can you please share the mpdev logs so that we can debug on our side. Thank you.

Regards,

Dinesh

---

It seems like they have been using Kubernetes 1.20.

Dinesh asked for the mpdev verify logs ([log-5644f650-0e14-481b-80c0-746ea7ef61ad.txt](https://github.com/jetstack/jetstack-secure-gcm/files/6967927/log-5644f650-0e14-481b-80c0-746ea7ef61ad.txt))

**Comment by maelvls** [comment]
I sent an email to Dinesh explaining that this error might be due to running 1.1, 1.3, and 1.4 simultaneously (email: https://groups.google.com/a/jetstack.io/g/cert-manager-maintainers/c/CipFiCJaVDg/m/RvW7HenyAQAJ, internal link)

**Comment by wallrj** [comment]
On Wednesday, 11 August 2021 at 19:28:45 UTC+1 Google Marketplace Onboarding Team wrote:
>     Hi Maël,
>     Thanks for the update. I re-triggered the verification for your submitted draft and the latest version passed at our verification service.
> 
>     Also, I've reviewed the latest version draft and published your listing on the GKE Marketplace. Please test and let me know if you have any questions or concerns. Thank you.
> 
>     Regards,
>     Dinesh 

Sounds like this was a temporary problem at their end.
