### ISSUE TITLE
Document how to update the cert-manager Helm chart templates

### ISSUE THREAD

**Issue by wallrj** [jetstack/jetstack-secure-gcm#67]
In #66 I renamed the existing charts directory, ran `helm pull --untar`, inspected the `git diff`, copied the new RBAC etc then applied https://github.com/jetstack/jetstack-secure-gcm/pull/66/commits/9904882130340b891bcb4fcc7132796b619c99b6

See https://github.com/jetstack/jetstack-secure-gcm/pull/66/commits for example

**Comment by maelvls** [comment]
I added one step to the "release process" in the release notes for 1.6.1-gcm.0. It goes like this:


- [x] ⚠️ Update the cert-manager chart:

  ```sh
  # From the jetstack-secure-gcm repo.
  cd chart/jetstack-secure-gcm/charts/
  rm -rf cert-manager
  helm pull jetstack/cert-manager --version 1.6.0 --untar
  ```

  Then, run the following:

  ```sh
  find cert-manager -type f -print0 | xargs -0 perl -i~ -pe 's/app\.kubernetes\.io\/name:(.*\")[a-z-._]+\.name(\".*)/app.kubernetes.io\/name:$1cert-manager.name$2/g'
  find cert-manager -type f -print0 | xargs -0 perl -i~ -nle 'print if !/^ *app:/'
  ```

  > **Explanation:**
  >
  > 1. The first command makes sure all the `app.kubernetes.io/name` are set to
  >    `cert-manager`. This is a "bug" in the cert-manager chart that we need to
  >    fix in the GCM chart to avoid seeing missing resources in GKE's
  >    Application UI.
  > 2. The second command removes all `app: ...` labels since these aren't used
  >    in GCM.

  Finally, add patches that make sense:

  ```sh
  git add -p
  ```

  Check that you haven't removed important things (like the GCM-specific Helm
  stuff added for the ubbagent).
